package com.PGN15.movieticketbooking.model;


import lombok.Data;//Generates getters,setters,toString(),equals(),hashCode() automatically
import lombok.NoArgsConstructor;//Generates a constructor with no parameters
import lombok.AllArgsConstructor;//Generates a constructor with all parameters

import java.util.UUID;//java Library Used to generate a unique user ID


//call
@Data
@NoArgsConstructor
@AllArgsConstructor

/**
 * Base User class.
 * Stores common user information.
 * Encapsulation is achieved through private attributes and public getters/setters (generated by Lombok @Data).
 */

public class BaseUser {
    private String userId;
    private String username;
    private String password; // In a real app, this should be hashed
    private String email;
    private String contactNumber;

    //Constructor
    public BaseUser(String username, String password, String email, String contactNumber) {
        this.userId = UUID.randomUUID().toString(); // Auto Generate a unique ID
        this.username = username;
        this.password = password;
        this.email = email;
        this.contactNumber = contactNumber;
    }

    /**
     * Converts BaseUser object to a CSV string for file storage.
     * Format: userId,username,password,email,contactNumber
     * CSV(CSV-Comma-Separated Values)string representation of the user.
     */
    //CSV-Comma-Separated Values

    //Serialization
    //Converts objects to CSV strings
    public String toCsvString() {
        return String.join(",",
                escapeCsv(userId),
                escapeCsv(username),
                escapeCsv(password), // Password stored as is for this project
                escapeCsv(email),
                escapeCsv(contactNumber));
    }

    //Deserialization
    //CSV string back into a BaseUser object by splitting the string
    public static com.PGN15.movieticketbooking.model.BaseUser fromCsvString(String csvString) {
        if (csvString == null || csvString.trim().isEmpty()) {
            return null;
        }
        String[] parts = csvString.split(",", 5); // Expect 5 parts
        if (parts.length < 5) {
            System.err.println("Malformed CSV string for BaseUser: " + csvString + ". Expected 5 parts, got " + parts.length);
            return null;
        }
        //return new BaseUser
        return new com.PGN15.movieticketbooking.model.BaseUser(parts[0], parts[1], parts[2], parts[3], parts[4]);
    }

    /**
     * Helper method to escape commas in CSV fields if necessary.
     * For this project, we assume fields do not contain commas or are handled by simple splitting.
     * A more robust solution would use a CSV library or quote fields.
     * @param field The string field to escape.
     * @return The escaped string.
     */
    //Prevent CSV Parsing Errors
    //Handle Quotes in Fields
    //Ensure Robustness
    protected String escapeCsv(String field) {
        if (field == null)
            return "";

        if (field.contains(",")) {
            return "\"" + field.replace("\"", "\"\"") + "\"";
        }
        return field;
    }
}
